-------------------------------------------------------------------------------------------
/*
  In this script contains Explain, Explain analyze in postgres.
  
  
  						EXPLAIN -> command displays the execution plan generated by the query planner for a given statement. 
  						Instead of returning the actual data rows, it shows a detailed breakdown of how PostgreSQL intends to scan 
  						tables, use indexes, join datasets, and sort results to execute your query.
  						
  						EXPLAIN ANALYZE ->  executes the query and generates a detailed report comparing the database's predicted 
  						plan with its real-world performance.
  						
						The difference
																	EXPLAIN						EXPLAIN ANALYZE
						Runs the query?						No — just shows the plan		Yes — actually executes it
						Shows estimated cost/rows?					Yes									Yes
						Shows actual time/row						No									Yes
						Safe on UPDATE/DELETE?						Yes						No — it really modifies data


*/

-------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------

explain 
select * from employeedata where dept = 'IT';

explain 
select 
	*,											
	dense_rank() over(),									-- same output
	rank() over(partition by e.dept order by e.salary desc), -- as this only slices the data into per-dept windows. But since there's still no ORDER BY inside that window, every row within each dept is also treated as tied.
	rank() over(partition by e.dept order by e.salary desc),
	dense_rank() over(partition by e.dept),
	dense_rank() over(partition by e.dept order by e.salary desc)
from employeedata e 

---------------------

explain analyze
select * from employeedata where dept = 'IT';


explain analyze
select 
	*,											
	dense_rank() over(),									-- same output
	rank() over(partition by e.dept order by e.salary desc),-- as this only slices the data into per-dept windows. But since there's still no ORDER BY inside that window, every row within each dept is also treated as tied.
	rank() over(partition by e.dept order by e.salary desc),
	dense_rank() over(partition by e.dept),
	dense_rank() over(partition by e.dept order by e.salary desc)
from employeedata e 

